---
version: '3.6'

x-besu-def:
  &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |

      cp "/config/IBFTgenesis.json" /config/genesis.json

      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,IBFT \
      --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,IBFT ;

x-redis-def:
  &redis-def
  image: redis:alpine

x-elasticsearch-def:
  &elasticsearch-def
  image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
  environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"
    - "discovery.type=single-node"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  cap_add:
    - IPC_LOCK

x-kibana-def:
  &kibana-def
  image: docker.elastic.co/kibana/kibana:7.14.1
  environment:
    ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    XPACK_MONITORING_ENABLED: "true"
    XPACK_MONITORING_COLLECTION_ENABLED: "true"
    SERVER_NAME: "localhost"
  depends_on:
    - elasticsearch
  links:
    - elasticsearch
  ports:
    - 5601:5601/tcp

x-logstash-def:
  &logstash-def
  build: ./logstash
  environment:
    - ES_HOST=http://elasticsearch:9200
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  depends_on:
    - redis
    - elasticsearch
  links:
    - redis
    - elasticsearch

x-filebeat-def:
  &filebeat-def
  build: ./filebeat
  environment:
    - ENV_NAME=dev
    - IP_ADDRESS=127.0.0.1
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  depends_on:
    - redis
  links:
    - redis
  volumes:
    - ./logs/besu/:/var/log/besu/

x-metricbeat-def:
  &metricbeat-def
  build: ./metricbeat
  environment:
    - ENV_NAME=dev
    - IP_ADDRESS=127.0.0.1
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  depends_on:
    - redis
  links:
    - redis

x-chainlensapi-ref:
  &chainlensapi-def
  image: web3labs/epirus-free-api:latest
  container_name: chainlensapi
  environment:
    - NODE_ENDPOINT=http://rpcnode:7545
    - MONGO_CLIENT_URI=mongodb://chainlensmongodb:27017
    - REINDEX_ENDPOINT=http://chainlensingestion/reindex/
    - MONGO_DB_NAME=epirus
    - MONGO_CREATE_INDICES=true
  depends_on:
    - chainlensmongodb

x-chainlensmongodb-ref:
  &chainlensmongodb-def
  image: mongo:5.0.8
  container_name: chainlensmongodb
  environment:
    - COMPOSE_HTTP_TIMEOUT=900
    - DOCKER_CLIENT_TIMEOUT=900
  entrypoint: mongod --bind_ip "0.0.0.0"

x-chainlensweb-ref:
  &chainlensweb-def
  image: web3labs/epirus-free-web:latest
  container_name: chainlensweb
  environment:
    - API_URL=/api
    - DISPLAY_NETWORK_TAB=disabled
  depends_on:
    - chainlensapi

x-chainlensingestion-ref:
  &chainlensingestion-def
  image: web3labs/epirus-free-ingestion:latest
  container_name: chainlensingestion
  environment:
    - NODE_ENDPOINT=http://rpcnode:7545
    - MONGO_CLIENT_URI=mongodb://chainlensmongodb:27017
    - MONGO_DB_NAME=epirus
  depends_on:
    - chainlensmongodb
    - chainlensweb

x-chainlensnginx-ref:
  &chainlensnginx-def
  image: nginx:latest
  container_name: chainlensnginx
  volumes:
    - ./chainlens/nginx.conf:/etc/nginx/nginx.conf
    - ./chainlens/5xx.html:/www/error_pages/5xx.html
  ports:
    - 8081:80
  depends_on:
    - chainlensapi
    - chainlensweb

x-ethsignerProxy-def:
  &ethsignerProxy-def
  image: consensys/ethsigner:${ETHSIGNER_VERSION:-latest}
  command: [
    "--chain-id=1337",
    "--http-listen-host=0.0.0.0",
    "--downstream-http-port=7545",
    "--downstream-http-host=rpcnode",
    "file-based-signer",
    "-k",
    "/opt/ethsigner/keyfile",
    "-p",
    "/opt/ethsigner/passwordfile"
  ]
  ports:
    - 7545

services:

  validator1:
    << : *besu-def
    ports:
      - 21001:7545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator1,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *besu-def
    ports:
      - 21002:7545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator2,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator2:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *besu-def
    ports:
      - 21003:7545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator3,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator3:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *besu-def
    ports:
      - 21004:7545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator4,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator4:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *besu-def
    container_name: rpcnode
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=rpcnode,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/rpcnode:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    ports:
      - 7545:7545/tcp
      - 7546:7546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15

  ethsignerProxy:
    << : *ethsignerProxy-def
    volumes:
      - ./config/ethsigner/password:/opt/ethsigner/passwordfile
      - ./config/ethsigner/key:/opt/ethsigner/keyfile
    depends_on:
      - validator1
      - rpcnode
    ports:
      - 17545:7545/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.40

  explorer:
    image: consensys/quorum-explorer:${QUORUM_EXPLORER_VERSION:-latest}
    volumes:
      - ./quorum-explorer/config.json:/app/config.json
      - ./quorum-explorer/.env.production:/app/.env.production
    depends_on:
      - rpcnode
    ports:
      - 25000:25000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.31

  chainlensapi:
    <<: *chainlensapi-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.53

  chainlensmongodb:
    <<: *chainlensmongodb-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.54

  chainlensingestion:
    <<: *chainlensingestion-def
    depends_on:
      - rpcnode
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.55

  chainlensweb:
    <<: *chainlensweb-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.56

  chainlensnginx:
    <<: *chainlensnginx-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.57

  prometheus:
    image: "prom/prometheus:v2.46.0"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.32

  grafana:
    image: "grafana/grafana:10.1.0"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.33

  loki:
    image: "grafana/loki:2.8.4"
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.34

  promtail:
    image: "grafana/promtail:2.8.4"
    volumes:
      - ./logs:/var/log
      - ./promtail/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35

  redis:
    << : *redis-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.42

  elasticsearch:
    << : *elasticsearch-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.43

  kibana:
    << : *kibana-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.44

  logstash:
    << : *logstash-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.45

  filebeat:
    << : *filebeat-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.46

  metricbeat:
    << : *metricbeat-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.47

volumes:
  public-keys:
  prometheus:
  grafana:
  splunk:
  ethlogger:
  blockscoutpostgres:

networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
